apiVersion: v2
name: tekton
description: A Helm chart for deploying tekton

type: application

version: 0.2.0

appVersion: "0.23.0"

dependencies:
  - name: tekton-operator
    version: 0.2.x
    repository: https://storage.googleapis.com/triggermesh-charts
    condition: tekton-operator.enabled
