apiVersion: v2
name: triggermesh
description: A Helm chart deploying TriggerMesh Open Source Components

type: application

version: 0.8.1

appVersion: "v1.25.0"

dependencies:
  - name: triggermesh-core
    version: 1.2.x
    repository: https://storage.googleapis.com/triggermesh-charts
    condition: triggermesh-core.enabled
    tags:
      - triggermesh
      - triggermesh-core
      - brokers
