apiVersion: v2
name: tm-cloud
description: A Helm chart for on-premise deployments of TriggerMesh cloud infrastructure

type: application

version: 0.6.0

appVersion: "v1.10.0"

dependencies:
  - name: keycloak
    version: 0.1.x
    repository: https://storage.googleapis.com/triggermesh-charts
    condition: keycloak.enabled
    tags:
      - authentication
  - name: triggermesh
    version: 0.5.x
    repository: https://storage.googleapis.com/triggermesh-charts
    condition: triggermesh.enabled
    tags:
      - triggermesh
      - knative
      - sources
      - targets
      - transformations
      - functions
  - name: koby
    version: 0.1.x
    repository: https://storage.googleapis.com/triggermesh-charts
    condition: koby.enabled
    tags:
      - triggermesh
      - koby
